/** @type {import('tailwindcss').Config} */
// const defaultTheme = require('tailwindcss/defaultTheme')
import defaultTheme from 'tailwindcss/defaultTheme'
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{react_vue_utils,ts,react_app,tsx,vue}",
  ],
  theme: {
    extend: {
      colors: {
        'grey-light': "var(--grey-light)",
        'grey-light-hover': "var(--grey-light-hover)",
        'grey-light-active': "var(--grey-light-active)",
        'grey-normal': "var(--grey-normal)",
        'grey-normal-hover': "var(--grey-normal-hover)",
        'grey-normal-active': "var(--grey-normal-active)",
        'orange-light': "#FFF4EC",
        'orange-light-hover': "#FFEFE2",
        'orange-light-active': "#FFDDC3",
        'orange-normal': "#FE913F",
        'orange-normal-hover': "#E58339",
        'orange-normal-active': "#CB7432",
        'green-light': '#F8FDFB',
        'green-light-hover': '#F4FCF8',
        'green-light-active': '#E8F8F1',
        'green-normal': '#B6EAD3',
        'green-normal-hover': '#A4D3BE',
        'green-normal-active': '#92BBA9',
        'green-dark': '#89B09E',
        'green-dark-hover': '#6D8C7F',
        'green-dark-active': '#52695F',
        'green-darker': '#40524A',
        'green-hover': '#6D8C7F',
        'green-34': "#34C759",
        'green-2f': "#2fc08f",
        'green-b6': "#B6EBD2",
        'yellow-fa': "#faedaa",
        // 涨跌语义色（CSS 变量驱动，便于 P1 按 locale 切换红涨/绿涨）
        'up': 'var(--color-up)',
        'down': 'var(--color-down)',
        'red-e6': "#E6374D",
        'red-ff': "#FFB7B7",
        'red-light': '#FFECEE',
        'red-light-hover': '#FFE2E6',
        'red-light-active': '#FFC3CA',
        'red-normal': '#FF3D55',
        'red-normal-hover': '#E6374D',
        'red-normal-active': '#CC3144',
        'purple-c1': "#c1c3ff",
        'grey-fa': "var(--grey-fa)",
        'grey-64': "var(--grey-64)",
        'grey-e6': "var(--grey-e6)",
        'grey-3f': "var(--grey-3f)",
        'grey-bd': "var(--grey-bd)",
        'grey-6f': "var(--grey-6f)",
        'grey-e7': "var(--grey-e7)",
        'grey-93': "var(--grey-93)",
        'grey-c9': "var(--grey-c9)",
        'grey-f0': "var(--grey-f0)",
        'grey-8d': "var(--grey-8d)",
        'grey-d1': "var(--grey-d1)",
        'grey-8e': "var(--grey-8e)",
        'grey-5a': "var(--grey-5a)",
        'grey-f4': "var(--grey-f4)",
        'black-19': "var(--black-19)",
        'orange-fa': "#FACA83",
        'blue-active': "#575873",
        'blue-32': "#32ADE6",
        // 语义主题 token（亮/暗由 :root 与 html.dark 翻转）；命名避开 text-/border- 内置工具冲突
        'app-bg': "var(--app-bg)",
        'surface': "var(--surface)",
        'surface-2': "var(--surface-2)",
        'line': "var(--border-base)",
        'content': "var(--text-base)",
        'muted': "var(--text-muted)",
        'faint': "var(--text-faint)",
      },
      borderColor: {
        // 无显式颜色的边框（含 preflight 默认）跟随主题，避免暗色下出现浅灰/白分隔线
        DEFAULT: 'var(--border-base)',
      },
      backgroundImage: theme => ({
        'gradient-primary': 'linear-gradient(213.44deg, #FCA454 -14.77%, #FF7A00 116.22%)',
        'gradient-purple': 'linear-gradient(90deg, #F98282 11.46%, #A65BFA 98.96%)',
        'img-home': 'url("@/assets/images/main-bg.svg")',
        'img-common': 'url("@/assets/images/main-bg1.svg")',
        'gradient-tab': 'linear-gradient(181.87deg, #FEFEFE -41.52%, #FEFEFE 114.96%)'
      }),
      boxShadow: theme => ({
        'tag-logo': '0px 3px 10px 0px #FFFFFF7D inset',
        'popper-tip': '0px 0px 12px rgba(0,0,0,0.12)',
        'tab': '0px 20px 40px 0px #373E7D1A',
        'insert-white': '1px 1000px 2px #ffffff inset;'
    })
    },
    fontSize: {
      'xs': ['10px', '14px'],
      'sm': ['12px', '16px'],
      'base': ['14px', '20px'],
      'lg': ['16px', '24px'],
      'xl': ['20px', '28px'],
      '2xl': ['24px', '32px'],
      '3xl': ['28px', '36px'],
      '4xl': ['32px', '40px'],
      'h1': ['32px', {lineHeight: '36px', fontWeight: '800',}],
      'h2': ['22px', {lineHeight: '26px', fontWeight: '700', letterSpacing: '-0.05em'}],
      'h3': ['16px', {lineHeight: '20px', fontWeight: '700', letterSpacing: '-0.02em'}],
      'h4': ['14px', {lineHeight: '16px', fontWeight: '400', letterSpacing: '-0.02em'}],
      'h5': ['14px', {lineHeight: '16px', fontWeight: '700', letterSpacing: '-0.02em'}],
    },
    screens: {
      'web': '804px',
      // 中间档：804–1080 侧栏图标化、隐藏右栏；≥1080 完整三栏
      'desk': '1080px',
      ...defaultTheme.screens,
    }
  },
  plugins: [],
}

