/** @type {import('tailwindcss').Config} */
const defaultTheme = require('tailwindcss/defaultTheme')
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,vue}",
  ],
  theme: {
    extend: {
      colors: {
        'grey-light': "#ebebeb",
        'grey-light-hover': "#e2e2e2",
        'grey-light-active': "#c2c2c2",
        'grey-normal': "#3b3b3b",
        'grey-normal-hover': "#353535",
        'grey-normal-active': "#2f2f2f",
        'orange-light': "#FFF4EC",
        'orange-light-hover': "#FFEFE2",
        'orange-light-active': "#FFDDC3",
        'orange-normal': "#FE913F",
        'orange-normal-hover': "#E58339",
        'orange-normal-active': "#CB7432",
        'green-light': '#F8FDFB',
        'green-light-hover': '#F4FCF8',
        'green-light-active': '#E8F8F1',
        'green-normal': '#B6EAD3',
        'green-normal-hover': '#A4D3BE',
        'green-normal-active': '#92BBA9',
        'green-dark': '#89B09E',
        'green-dark-hover': '#6D8C7F',
        'green-dark-active': '#52695F',
        'green-darker': '#40524A',
        'green-hover': '#6D8C7F',
        'green-34': "#34C759",
        'green-2f': "#2fc08f",
        'green-b6': "#B6EBD2",
        'yellow-fa': "#faedaa",
        'red-e6': "#E6374D",
        'red-ff': "#FFB7B7",
        'red-light': '#FFECEE',
        'red-light-hover': '#FFE2E6',
        'red-light-active': '#FFC3CA',
        'red-normal': '#FF3D55',
        'red-normal-hover': '#E6374D',
        'red-normal-active': '#CC3144',
        'purple-c1': "#c1c3ff",
        'grey-fa': "#FAFAFA",
        'grey-64': "#646464",
        'grey-e6': "#E6E8EC",
        'grey-3f': "#3F3F3F",
        'grey-bd': "#BDBDBD",
        'grey-6f': "#6F6F6F",
        'grey-e7': "#E7E7E7",
        'grey-93': "#9395A4",
        'grey-c9': "#C9C9C9",
        'grey-f0': "#F0F0F0",
        'grey-8d': "#8D8D8D",
        'grey-d1': "#D1D1D1",
        'grey-8e': "#8E8E93",
        'grey-5a': "#5A5A5A",
        'grey-f4': "#F4F4F4",
        'black-19': "#191C32",
        'orange-fa': "#FACA83",
        'blue-active': "#575873",
        'blue-32': "#32ADE6"
      },
      backgroundImage: theme => ({
        'gradient-primary': 'linear-gradient(213.44deg, #FCA454 -14.77%, #FF7A00 116.22%)',
        'gradient-purple': 'linear-gradient(90deg, #F98282 11.46%, #A65BFA 98.96%)',
        'img-home': 'url("@/assets/images/main-bg.svg")',
        'img-common': 'url("@/assets/images/main-bg1.svg")',
        'gradient-tab': 'linear-gradient(181.87deg, #FEFEFE -41.52%, #FEFEFE 114.96%)'
      }),
      boxShadow: theme => ({
        'tag-logo': '0px 3px 10px 0px #FFFFFF7D inset',
        'popper-tip': '0px 0px 12px rgba(0,0,0,0.12)',
        'tab': '0px 20px 40px 0px #373E7D1A',
        'insert-white': '1px 1000px 2px #ffffff inset;'
    })
    },
    fontSize: {
      'xs': ['10px', '14px'],
      'sm': ['12px', '16px'],
      'base': ['14px', '20px'],
      'lg': ['16px', '24px'],
      'xl': ['20px', '28px'],
      '2xl': ['24px', '32px'],
      '3xl': ['28px', '36px'],
      '4xl': ['32px', '40px'],
      'h1': ['32px', {lineHeight: '36px', fontWeight: '800',}],
      'h2': ['22px', {lineHeight: '26px', fontWeight: '700', letterSpacing: '-0.05em'}],
      'h3': ['16px', {lineHeight: '20px', fontWeight: '700', letterSpacing: '-0.02em'}],
      'h4': ['14px', {lineHeight: '16px', fontWeight: '400', letterSpacing: '-0.02em'}],
      'h5': ['14px', {lineHeight: '16px', fontWeight: '700', letterSpacing: '-0.02em'}],
    },
    screens: {
      'web': '1104px',
      ...defaultTheme.screens,
    }
  },
  plugins: [],
}

